#ifndef __EXTENSIONSYSTEM_GLOBAL_H__
#define __EXTENSIONSYSTEM_GLOBAL_H__

#include <QtGlobal>

#if defined(EXTENSIONSYSTEM_LIBRARY)
#  define EXTENSIONSYSTEM_EXPORT Q_DECL_EXPORT
#elif defined(EXTENSIONSYSTEM_STATIC_LIBRARY)
#  define EXTENSIONSYSTEM_EXPORT
#else
#  define EXTENSIONSYSTEM_EXPORT Q_DECL_IMPORT
#endif


#endif
